### ISSUE TITLE
Microphone Component

### ISSUE THREAD

**Issue by mattrwang** [Northeastern-Electric-Racing/Nero-2.0#102]
### Description

Once push-to-talk is implemented, display the microphone icon whenever it is active.

### Acceptance Criteria

- [ ] Microphone icon is displayed if and only if push-to-talk is active

### Proposed Solution

- [ ] create controller for icon
- [ ] have a Q_PROPERTY that is updated whenever push-to-talk is activated

**Comment by jr1221** [comment]
after fsae
