### ISSUE TITLE
Speed Mode - Timer Display

### ISSUE THREAD

**Issue by Peyton-McKee** [Northeastern-Electric-Racing/Nero-2.0#58]
### Description

We want to show the current runs time, the last runs time, and then the historical fastest run. 

### Acceptance Criteria

Takes in the current run time, the last run time and the fastest run time,
looks like mock

### Proposed Solution

^
epic #56 

### Mocks

<img width="276" alt="Screenshot 2024-01-24 at 11 34 22 PM" src="https://github.com/Northeastern-Electric-Racing/Nero-2.0/assets/113635669/d813d892-e477-4db1-b217-a2b873f693c6">

**Comment by mliam0608** [comment]
![image](https://github.com/Northeastern-Electric-Racing/Nero-2.0/assets/138416854/9b61bc6d-d8ab-41a8-9b12-41607aca93cf)
New image of adjusted text.
