### ISSUE TITLE
Performance Mode - Lap Time Button

### ISSUE THREAD

**Issue by mattrwang** [Northeastern-Electric-Racing/Nero-2.0#97]
### Description

Starts recording lap time when enter/return is pressed, and stops recording when it is pressed again. Stores and displays fastest lap time, last lap time, and current lap time.

### Acceptance Criteria

- [ ] starts recording time the first time enter/return is pressed
- [ ] stops recording the second time it is pressed
- [ ] stores fastest, last, and current times
- [ ] displays times on performance screen
- [ ] handle edge cases (no time has been recorded)

### Proposed Solution

- [ ] use QElapsedTimer
- [ ] create controller files that have Q_PROPERTYs that store times
- [ ] ask chatGPT/google

**Comment by jr1221** [comment]
Pretty sure this would be for efficiency no?

**Comment by mattrwang** [comment]
> Pretty sure this would be for efficiency no?

all the lap time stuff is on the performance screen

**Comment by jr1221** [comment]
I feel like knowing your time during performance isn't gonna be a big deal bc the support crew can tell you it.  I thought it would be more useful in efficiency when you are doing many laps over and over.

**Comment by mattrwang** [comment]
@Peyton-McKee what do you think?

**Comment by jr1221** [comment]
Before fsae would be nice --> hook up performance mode to "User/Laps/Time", also add the previous 3 laps to endurance replacing the spot with reverse.  also limit the string length and make sure garbled text wont break anything.
